const {
  APPLICATION_MENUS,
  VIEW_MENUS,
  BASE_URL,
  HOME_URL,
  TRAINING_INFO_PATH,
  TRAINING_INFO_URL,
  YEBIGUN_ENDPOINTS,
  detectSessionState,
  diffTrainings,
  inspectYebigunPage,
  parseGenericTable,
  parseInquiry,
  parseTrainingInfo,
  textPreview,
  trainingsForYear,
} = require("./parse");
const {
  buildChromeLaunchCommand,
  connectToChrome,
  fetchInquiry,
  fetchTrainingInfo,
  inspectPage,
  openApplicationMenu,
} = require("./browser");
const {
  COMPARABLE_FIELDS,
  DEFAULT_HISTORY_PATH,
  diffYears,
  getYear,
  listYears,
  recordYear,
} = require("./history");

module.exports = {
  APPLICATION_MENUS,
  VIEW_MENUS,
  BASE_URL,
  HOME_URL,
  TRAINING_INFO_PATH,
  TRAINING_INFO_URL,
  YEBIGUN_ENDPOINTS,
  COMPARABLE_FIELDS,
  DEFAULT_HISTORY_PATH,
  buildChromeLaunchCommand,
  connectToChrome,
  detectSessionState,
  diffTrainings,
  diffYears,
  fetchInquiry,
  fetchTrainingInfo,
  getYear,
  inspectPage,
  inspectYebigunPage,
  listYears,
  openApplicationMenu,
  parseGenericTable,
  parseInquiry,
  parseTrainingInfo,
  recordYear,
  textPreview,
  trainingsForYear,
};
